### ISSUE TITLE
hero deploy 部署错误

### ISSUE THREAD

**Issue by ming15** [wuchong/jacman#143]
当我使用hexo g生成好博客文件，然后使用hexo d进行部署的时候，却把master部署到了gh-pages上。
我的配置如下
```
deploy:
  type: git
  repo: git@github.com:ming15/blog-website.git
  branch: gh-pages
```
这是hero的问题还是需要在jacman中设置？
