### ISSUE TITLE
自定义按钮遇到的问题

### ISSUE THREAD

**Issue by wanggnim** [wuchong/jacman#90]
我进行了如下定义
```
menu:
  Home: /
  Archives: /archives
  jvm7: /jvm7
```
然后我创建了`source\jvm7\index.md`文件
```
layout: jvm7
title: jvm7
---
```

但是我生成的页面点击`jvm7`按钮时，却没有显式出`source\jvm7`下其他的文章,这是怎么回事？
